### ISSUE TITLE
Consider 'platinum onboarding' sample

### ISSUE THREAD

**Issue by dstaudt** [CiscoDevNet/awesome-xapi#11]
Interesting sample here: https://github.com/CiscoSE/platinum-onboard/tree/master/ceapi
 
However uses undocumented device API (/web/api) to get proximity user details - may need to wait until that capability is exposed in supported APIs (or just pass for now)

**Comment by ObjectIsAdvantag** [comment]
Great finding, let's wait for an official support for proximity

As there is no ETA/visibility, I propose to close, and reopen when appropriate.
